import type { Metadata } from "next";
import SuperAdminNavbar from "@/app/_components/super-admin/navbar";

export const metadata: Metadata = {
  title: "Secure Track - Super Admin",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function SuperAdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <SuperAdminNavbar />
      <div className="m-10">{children}</div>
    </>
  );
}
