import type { Metadata } from "next";
import AdminNavbar from "@/app/_components/admin/navbar";

export const metadata: Metadata = {
  title: "Secure Track - Admin",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function AdminLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <AdminNavbar />
      <div className="p-10">{children}</div>
    </>
  );
}
